export const ADD_STAFF = 'ADD_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';
export const LOADING_STAFF = 'LOADING_STAFF';
export const LOADING_DEPARTMENT = 'LOADING_DEPARTMENT';
export const LOADING_SALARYSHEET = 'LOADING_SALARYSHEET';