export const ADD_DISHES = 'ADD_DISHES';
export const DELETE_DISHES = 'DELETE_DISHES';
export const LOADING_DISHES = 'LOADING_DISHES';
export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const LOADING_LEADERS = 'LOADING_LEADERS';
export const LOADING_PROMOTIONS = 'LOADING_PROMOTIONS';